# .goreleaser.yml
# This is the corrected configuration file for GoReleaser.

# The project name, used for the final binary and archives.
project_name: om

before:
  hooks:
    - go mod tidy

builds:
  - # The ID of the build.
    id: om
    # The path to the main package.
    main: .
    # The final binary name will be 'om' (GoReleaser adds .exe for Windows).
    binary: om
    # GOOS and GOARCH to build for.
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Optional ldflags.
    ldflags:
      - -s -w

archives:
  - id: om
    # This name template will now produce archives like 'om_0.6.0_windows_amd64.tar.gz'
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew tap configuration
brews:
  - # The name of the formula file will be 'open-workbench-platform.rb'.
    name: open-workbench-platform
    repository:
      owner: jashkahar
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/jashkahar/open-workbench-platform"
    description: "A powerful CLI for scaffolding modern web applications."
    license: "MIT"
    test: |
      # The test will now correctly call the 'om' command.
      system "#{bin}/om --version"

# Scoop bucket configuration
scoops:
  - # The name of the manifest file will be 'open-workbench-platform.json'.
    name: open-workbench-platform
    repository:
      owner: jashkahar
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/jashkahar/open-workbench-platform"
    description: "A powerful CLI for scaffolding modern web applications."
    license: "MIT"

release:
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
